services:
  app:
    image: tms/c22
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - 8090:8080

  db:
    image: postgres:16
    container_name: db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5433:5432

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080


volumes:
  postgres-data: { }
